# baseURL = 'https://example.org/'
# languageCode = 'en-us'
# title = "Martin's First Hugo Site"
# # theme = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
# sectionPagesMenu = 'main'

# theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
# theme = ["mainroad"]
# theme = ["github.com/razonyang/hugo-theme-bootstrap"]
# [caches]
#   [caches.images]
#     dir = ':cacheDir/images'

# [module]
# [[module.imports]]
# disable = false
# ignoreConfig = false
# ignoreImports = false
# path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

# [[module.imports]]
#     path= "github.com/imfing/hextra"

# [[module.imports]]
#     path = "github.com/razonyang/hugo-theme-bootstrap/v2"